### ISSUE TITLE
Improve speed of SVM retriever index creation

### ISSUE THREAD

**Issue by PineappleExpress808** [PineappleExpress808/auto-evaluator#7]
Currently SVM retriever has a `create_index` def that will embed a list of chunks:
```
def create_index(contexts: List[str], embeddings: Embeddings) -> np.ndarray:
    return np.array([embeddings.embed_query(split) for split in contexts])
```

See code:
https://github.com/hwchase17/langchain/blob/f1d15b4a75238eb56e386608b7f631a853a803e0/langchain/retrievers/svm.py#L17
 
This is quite slow (> 10 min on ~2k splits).

Tried `multiprocessing`, but appears to hang w/:

```
Process SpawnPoolWorker-74:
Traceback (most recent call last):
  File "/Users/31treehaus/opt/anaconda3/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/31treehaus/opt/anaconda3/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/31treehaus/opt/anaconda3/envs/ml/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/31treehaus/opt/anaconda3/envs/ml/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'embed_query' on <module '__main__' (built-in)>
```

Tried a dataframe `apply` to parallelize, but no latency improvement.

Need to carve out more time to look into this.

**Comment by PineappleExpress808** [comment]
Done! 

https://github.com/hwchase17/langchain/pull/3192
